#!/bin/sh

# The passed parameters are:
#   $1 = The Binary Directory where everything is located
#   $2 = The File to change

CC=$1/bin/g++
LFLAGS="-I$1/LocalFiles"
CCFLAGS="-c --dump-tree-original-raw -I$1/lib"
PARSER=$1/bin/parser
SED=sed

if [ ! -f $2 ]; then
    echo "[ERROR] $1 is not a regular file"
    exit 6
fi

# Modified to deal with files in different directories
input=$2
justTheBasename=`basename $2`
prefix_input=${input%.*}

$CC $CCFLAGS $LFLAGS $input
if [ $? -ne 0 ]; then
    echo "[ERROR] on $CC"
    echo "exiting..."
    exit 5
fi

if [ ! -f $justTheBasename.t02.original ]; then
    echo "[ERROR] $justTheBasename.t02.original doesn't exist !"
    echo "Is the file empty?"
    exit 4
fi

cat $justTheBasename.t02.original > $prefix_input.ast
echo ";; zEvilEOF" >> $prefix_input.ast
if [ $? -ne 0 ]; then
    echo "[ERROR] on $SED"
    echo "exiting..."
    exit exit 3
fi

#tail $prefix_input.ast
if [ ! -f $prefix_input.ast ]; then
    echo "[ERROR] $prefix_input.ast doesn't exist !"
    exit  2
fi

$PARSER $prefix_input.ast $prefix_input.suif > /dev/null
if [ ! -f $prefix_input.suif ]; then
    echo "[ERROR] $prefix_input.suif doesn't exist !"
    exit 1
fi

rm -f *.o a.out *.ast *.t02.original
exit 0
